"""initial

Revision ID: 9cf4d75a2d43
Revises: 
Create Date: 2023-11-18 21:35:07.582105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9cf4d75a2d43"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "time_visited", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "time_visited", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
